apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "helloworld.example.com"
    http:
      paths:
      - pathType: Prefix
        path: "/test"
        backend:
          service:
            name: nginx-service
            port:
              number: 80