apiVersion: test.orange.com/v1
kind: HelloWorld
metadata:
  labels:
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/instance: helloworld-sample
    app.kubernetes.io/part-of: orange-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orange-operator
  name: helloworld-sample
spec:
   image: nginx
   replicas: 2
   ingressHostname: hello.world.com
  # TODO(user): Add fields here
